export const SERVICES = [
  "Haircut & Style",
  "Blowout",
  "Updo / Special Occasion",
  "Bridal Hair",
  "Single Process Color",
  "Color & Highlights",
  "Full Highlights",
  "Partial Highlights",
  "Balayage",
  "Ombre",
  "Color Correction",
  "Glaze / Gloss",
  "Deep Conditioning Treatment",
  "Keratin Treatment",
  "Brazilian Blowout",
  "Hair Extensions",
  "Manicure",
  "Pedicure",
  "Gel Manicure / Pedicure",
  "Dip Powder Nails",
  "Nail Art",
  "Facial",
  "Chemical Peel",
  "Microdermabrasion",
  "Dermaplaning",
  "Microneedling",
  "Massage",
  "Swedish Massage",
  "Deep Tissue Massage",
  "Hot Stone Massage",
  "Aromatherapy Massage",
  "Eyebrow Shaping",
  "Eyebrow Tinting",
  "Eyelash Extensions",
  "Eyelash Lift & Tint",
  "Waxing (Brows, Lip, Chin)",
  "Waxing (Legs, Arms, Underarms)",
  "Bikini / Brazilian Wax",
  "Makeup Application",
  "Bridal Makeup",
  "Spray Tan",
];
